import {Link} from 'react-router-dom'
import {PortableText} from '@portabletext/react'
import {imageUrl} from '../data/sanity'
import {formatDateTime, formatDayMonth, formatCompactDateTime, isPast} from '../lib/date'
import {safeExternalUrl} from '../lib/content'
import {useLocale} from '../i18n'

export const portableComponents = {marks: {link: ({value, children}) => { const href = safeExternalUrl(value?.href); return href ? <a href={href} target="_blank" rel="noreferrer">{children}</a> : <>{children}</> }}}
export function RichText({value}) { return value?.length ? <div className="prose"><PortableText value={value} components={portableComponents}/></div> : null }
const srcSet=(source,square=false)=>[480,800,1200].map(w=>`${imageUrl(source,w,square?w:undefined)} ${w}w`).join(', ')
export function Poster({production,size=600}){const {t}=useLocale();const src=imageUrl(production.poster,size,size);return src?<img className="poster" src={src} srcSet={srcSet(production.poster,true)} sizes="(max-width: 560px) 100vw, (max-width: 900px) 50vw, 33vw" alt={production.poster?.alt||`${t.imageLabel} ${production.title}`} loading="lazy" decoding="async" width={size} height={size}/>:<div className="poster placeholder" role="img" aria-label={`${t.imageMissing} ${production.title}`}><span>{production.title}</span></div>}
export function CoverImage({production}){const {t}=useLocale();const mobileSource=production.coverImage||production.desktopCoverImage||production.poster;const desktopSource=production.desktopCoverImage;const src=imageUrl(mobileSource,758,432);return src?<picture className={`production-cover ${desktopSource?'has-desktop-cover':''}`}>{desktopSource&&<source media="(min-width: 801px)" srcSet={imageUrl(desktopSource,1111,337)}/>}<img className="cover-image" src={src} srcSet={!desktopSource?[758,1111].map(w=>`${imageUrl(mobileSource,w,Math.round(w*432/758))} ${w}w`).join(', '):undefined} sizes="(max-width: 800px) 100vw, 1111px" alt={(desktopSource||mobileSource)?.alt||`${t.coverLabel} ${production.title}`} fetchPriority="high" width="758" height="432"/></picture>:<div className="cover-image placeholder" role="img" aria-label={`${t.coverMissing} ${production.title}`}><span>{production.title}</span></div>}
export function ImageHero({image,className='',children}){const src=imageUrl(image,1920,900);return <section className={`visual-hero ${src?'has-image':''} ${className}`.trim()}>{src&&<img className="hero-media" src={src} srcSet={[960,1440,1920].map(w=>`${imageUrl(image,w,Math.round(w*900/1920))} ${w}w`).join(', ')} sizes="100vw" alt={image?.alt||''} fetchPriority="high" width="1920" height="900"/>}<div className="visual-hero-content page-shell">{children}</div></section>}
export function Status({status,past}){const {t}=useLocale();const label=past?t.completed:status==='soldOut'?t.soldOut:status==='cancelled'?t.cancelled:t.available;return <span className={`status ${past?'past':status}`}>{label}</span>}
export function ProductionCard({production,nextEvent,compactNextDate=false}){const {t,path,locale}=useLocale();return <article className="production-card"><Link to={path('productions',production.slug)}><Poster production={production}/><div><p className="eyebrow">{production.category}</p><h3>{production.title}</h3><p>{production.summary}</p>{nextEvent&&<p className="next-date">{t.next}: {compactNextDate?formatDayMonth(nextEvent.startsAt,locale):formatDateTime(nextEvent.startsAt,locale)}</p>}</div></Link></article>}
export function EventRow({event,onIcs,compactDate=false,hideStage=false}){const {t,path,locale}=useLocale();const past=isPast(event.startsAt);const canBuy=!past&&event.status==='available';return <article className="event-row"><div><time dateTime={event.startsAt}>{compactDate?formatCompactDateTime(event.startsAt,locale):formatDateTime(event.startsAt,locale)}</time><p>{event.production.title}{!hideStage&&event.stage?.name&&` · ${event.stage.name}`}</p></div><Status status={event.status} past={past}/><div className="row-actions">{onIcs&&<button className="calendar-icon-button" onClick={()=>onIcs(event)} aria-label={t.addCalendar} title={t.addCalendar}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3v3M17 3v3M4 9h16M5 5h14a1 1 0 0 1 1 1v14H4V6a1 1 0 0 1 1-1Z"/><path d="M12 12v6M9 15h6"/></svg></button>}{canBuy&&safeExternalUrl(event.ticketUrl)?<a className="button" href={safeExternalUrl(event.ticketUrl)} target="_blank" rel="noreferrer">{t.buyTickets}</a>:canBuy&&<Link className="text-link" to={path('contact')}>{t.ticketInfo}</Link>}</div></article>}
export function Loading(){const {t}=useLocale();return <div className="state" aria-live="polite">{t.loading}</div>}
export function ErrorState({message,retry}){const {t}=useLocale();return <div className="state"><h1>{t.errorTitle}</h1><p>{message==='load-error'?t.loadError:message||t.noContent}</p><button className="button" onClick={retry}>{t.retry}</button></div>}
export function Empty({children}){const {lang}=useLocale();return <p className="empty">{children||(lang==='en'?'No content is currently available in English.':'Δεν υπάρχει διαθέσιμο περιεχόμενο.')}</p>}
